name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1
      - name: Usa Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm install
      - name: npm run build
        run: |
          npm run build --if-present
      - name: build readme
        run: |
          npm run create-readme
          git config user.name ${{ secrets.USERNAME }}
          git config user.email ${{ secrets.USER_EMAIL }}
          git add readme.md
          git commit -m "(📚 test) Update README.md by GH Actions"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/AXIOS-click/backend-ecommerce.git

      - name: npm test
        run: |
          npm test
